### ISSUE TITLE
how to get output the output?

### ISSUE THREAD

**Issue by AbbeKamalov** [dstathis/fastprocess#5]
```
from fastprocess import FastProcess

FastProcess(['./mycommand', 'arg'])

<fastprocess.fastprocess.FastProcess at 0x7f8af49c4320>
```

how can I get the actual output from my command via FastProcess?

**Comment by dstathis** [comment]
@mutal Sorry I haven't looked here in a while. Output will be printed to standard out. If you want to capture it you can use stdout=x where x is a file like object.

**Comment by W2NJL** [comment]
Is there any way to assign the output to a variable?  I am very intrigued by this as I definitely think subprocess is taking too long for the purpose I am using it for.

**Comment by dstathis** [comment]
@W2NJL I looked in to this a bit and it looks like it is not as trivial as I had hoped. I will definitely be pushing some changes to make it easier but for the time being you can do something like this:

```
>>> from fastprocess import FastProcess
>>> import os
>>> r, w = os.pipe()
>>> pid = FastProcess(['echo', 'hello', 'world'], stdout=os.fdopen(w))
>>> os.fdopen(r).read()
'hello world\n'
```

**Comment by W2NJL** [comment]
> @W2NJL I looked in to this a bit and it looks like it is not as trivial as I had hoped. I will definitely be pushing some changes to make it easier but for the time being you can do something like this:
> 
> ```
> >>> from fastprocess import FastProcess
> >>> import os
> >>> r, w = os.pipe()
> >>> pid = FastProcess(['echo', 'hello', 'world'], stdout=os.fdopen(w))
> >>> os.fdopen(r).read()
> 'hello world\n'
> ```

Thanks so much for the quick response!
